title                    : "Tween with Smin!"
title_separator          : "-"
name                     : &name "Smin:D"
description              : &description "personal description"
url                      : https://tween-with-smin.github.io/academicpages.github.io
